version: '3.4'

services:
  api:
    build: .
    command: python ./manage.py runserver 0.0.0.0:9000
    ports:
      - 9000:9000
    volumes:
      - .:/app/
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings