# Generated by Django 3.1.3 on 2020-11-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0', '0005_auto_20201127_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AddField(
            model_name='productcollection',
            name='products',
            field=models.ManyToManyField(to='apiv0.Product'),
        ),
    ]
