# Generated by Django 3.1.3 on 2020-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0', '0010_auto_20201129_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
